project:
  type: book
  output-dir: docs
  
book:
  title: "DataLab for causal inference"
  author: "Daniel Fernandez"
  date: last-modified
  reader-mode: true
  page-footer:
    left: |
      This book was built with 💕 and <a href="https://quarto.org/">Quarto</a>.
    right: |
       DataLab for causal inference
  cover-image: cover.png
  favicon: cover.png
  
  chapters:
    - index.qmd
    - capitulos/intro.qmd
    
    - part: capitulos/capitulo1.qmd
      chapters:
        - capitulos/Capítulo1.1.qmd
        - capitulos/Capítulo1.2.qmd
        - capitulos/Capítulo1.3.qmd
        - capitulos/Capítulo1.4.qmd
        - capitulos/Capítulo1.5.qmd
        - capitulos/Capítulo1.6.qmd
    
    - part: capitulos/Capítulo2.qmd
      chapters:
        - capitulos/Capítulo2.1.qmd
        - capitulos/Capítulo2.2.qmd
        - capitulos/Capítulo2.3.qmd
        - capitulos/Capítulo2.4.qmd

    - part: capitulos/Capítulo3.qmd

    - part: capitulos/Capítulo4.qmd

    - part: capitulos/Capítulo5.qmd

    - part: capitulos/Capítulo6.qmd

    - part: capitulos/Capítulo7.qmd

    - part: capitulos/Capítulo8.qmd

    - part: capitulos/Capítulo9.qmd

    - part: capitulos/Capítulo10.qmd

    - part: capitulos/Capítulo11.qmd

    - part: capitulos/Capítulo12.qmd

    - part: capitulos/Capítulo13.qmd

    - part: capitulos/Capítulo14.qmd

    - part: capitulos/Capítulo15.qmd

    - part: capitulos/Capítulo16.qmd

    - part: capitulos/Capítulo17.qmd

    - part: capitulos/Capítulo18.qmd

    - part: capitulos/Capítulo19.qmd

    - part: capitulos/Capítulo20.qmd


format:
  html:
    theme:
      - default
    code-link: true
    
    author-meta: "Daniel Fernandez"
    include-in-header: "plausible.html"
    callout-appearance: default

editor: visual