project:
  type: book
  output-dir: docs
  
book:
  title: "DataLab for causal inference"
  author: "Daniel Fernandez"
  date: last-modified
  reader-mode: true
  page-footer:
    left: |
      DataLab was written by Daniel Fernandez.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png
  
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: summary.qmd
      chapters:
        - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true

    author-meta: "Daniel Fernandez"
    include-in-header: "plausible.html"
    callout-appearance: simple

editor: visual