project:
  type: book
  output-dir: docs
  
book:
  title: "DataLab for causal inference"
  author: "Daniel Fernandez"
  date: last-modified
  favicon: logo.png
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  lumo-html: 
    logo: "logo.png"                
    github-repo: "https://github.com"   
    primary-color: "#69b3a2" # b5cef7   69b3a2
    self-contained: true
    is-particlejs-enabled: true  # Optional: display interactive particles 
    bg-image: ""             # Optional: link to an image for the header background
    embed-resources: true
    toc-title: 'Contenido'
    self-contained-math: true
    theme: cosmo
    code-copy: true
    cover-image: cover.png
