project:
  type: book
  output-dir: docs
  
book:
  title: "DataLab for causal inference"
  author: "Daniel Fernandez"
  date: last-modified
  reader-mode: true
  page-footer:
    left: |
      This book was built with 💕 and <a href="https://quarto.org/">Quarto</a>.
    right: |
       DataLab for causal inference
  cover-image: cover.png
  favicon: cover.png
  
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: Capítulo1.qmd
      chapters:
        - Capítulo1.1.qmd
        - Capítulo1.2.qmd
        - Capítulo1.3.qmd
        - Capítulo1.4.qmd
        - Capítulo1.5.qmd
        - Capítulo1.6.qmd
    
    - part: Capítulo2.qmd
      chapters:
        - Capítulo2.1.qmd
        - Capítulo2.2.qmd

format:
  html:
    theme:
      - default
    code-link: true
    
    author-meta: "Daniel Fernandez"
    include-in-header: "plausible.html"
    callout-appearance: default

editor: visual