# Tipos de estudios de investigación 

| En investigación científica, los estudios pueden clasificarse en dos grandes categorías: primarios y secundarios. Los estudios primarios son aquellos en los que el investigador obtiene datos de manera directa o indirecta, ya sea a partir de pacientes, poblaciones, animales, microorganismos o cualquier otra fuente de información biológica o clínica. Estos estudios son la base del conocimiento científico, ya que permiten generar evidencia nueva a partir de la observación y experimentación.

Por otro lado, los estudios secundarios no generan datos originales, sino que analizan y sintetizan información previamente publicada. Se basan en la revisión de estudios primarios con el fin de extraer conclusiones más amplias, evaluar tendencias o generar recomendaciones basadas en la evidencia acumulada. Ejemplos de este tipo de estudios incluyen las revisiones sistemáticas y los metaanálisis, los cuales son fundamentales para la toma de decisiones clínicas y el desarrollo de guías de práctica médica.

Una de las clasificaciones más tradicionales dentro de los estudios primarios es la que los divide en observacionales y experimentales. Esta distinción es ampliamente utilizada en la literatura científica y en diversas herramientas metodológicas clave. Por ejemplo, las directrices de [EQUATOR Network](https://www.equator-network.org/) para la elaboración de reportes de investigación, así como instrumentos para la evaluación del riesgo de sesgo y/o la calidad metodológica, se basan en esta clasificación para establecer diferentes criterios de valoración.


## Referencia

1. Torales Julio, Barrios Iván. Diseño de investigaciones: algoritmo de clasificación y características esenciales. Med. clín. soc.  [Internet]. 2023  Dec [cited  2025  Feb  09] ;  7( 3 ): 210-235. Available from: [https://doi.org/10.52379/mcs.v7i3.349](https://doi.org/10.52379/mcs.v7i3.349)

